apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-managment-contro
  labels:
    app: rest
    role: rest-client
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rest
        role: rest-client
        tier: backend
    spec:
      containers:
      - name: mongo-managment
        image: djob195/mongo-managment
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "PROD"
        - name: NAMEDB
          value: "iarna"
        - name: URLDB
          value: "mongodb://admin:admin123456@ds119304.mlab.com:19304" 
        - name: CADUCIDAD_TOKEN
          value: "2592000"      
        - name: SEED
          value: "3sT3-3S-3L-S33d-D3-Pr0duCc10N-p4R4-t0K3n"       
        - name: DESDE
          value: "0"     
        - name: LIMITE
          value: "5"      
        - name: SMTP_HOST
          value: "smtp.gmail.com"   
        - name: SMTP_PORT
          value: "465"   
        - name: SMTP_SECURE
          value: "true"   
        - name: SMTP_AUTH_USER
          value: "djob195@gmail.com"   
        - name: SMTP_AUTH_PASS
          value: "22880207DiegoOrellana"                                                                                           
        ports:
        - containerPort: 8080