apiVersion: v1
kind: Service
metadata:
  name: mongo-managment-service
  labels:
    app: rest
    role: rest-client
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: rest
    role: rest-client
    tier: backend