apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-managment-contro
  labels:
    app: rest
    role: rest-client
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rest
        role: rest-client
        tier: backend
    spec:
      containers:
      - name: mongo-managment
        image: djob195/mongo-managment
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: ""
        - name: NODE_ENV
          value: ""
        - name: NAMEDB
          value: ""
        - name: URLDB
          value: "" 
        - name: CADUCIDAD_TOKEN
          value: ""      
        - name: SEED
          value: ""       
        - name: DESDE
          value: ""     
        - name: LIMITE
          value: ""      
        - name: SMTP_HOST
          value: ""   
        - name: SMTP_PORT
          value: ""   
        - name: SMTP_SECURE
          value: ""   
        - name: SMTP_AUTH_USER
          value: ""   
        - name: SMTP_AUTH_PASS
          value: ""      
        - name: ADMIN_PASSWORD
          value: ""                                                                                         
        ports:
        - containerPort: 8080